[package]
name = "github-actions-test"
version = "0.1.0"
authors = ["Robert O'Callahan <robert@ocallahan.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
